version: '3.8'

services:
  ml_pipeline:
    image: python:3.9.18-slim
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["python", "run_pipeline.py"]

  streamlit_app:
    image: python:3.9.18-slim
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: ["streamlit", "run", "streamlit_app.py"]
